# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1da616d0956bb628acf08caec901d5632e362ffb13b9bc301cd407de46632425b97bdeb0a37a5ea7a78b5fc15c773dd515a6f2ea4c99311f65d18bc04e8170e

test:
  secret_key_base: c57a3be6f5a99107f2cd873a5098de4ff8ada1c4bfb2b3ff98025e275744f3f93988d16657c562b9615df9c61d36f2ed7a1a630f59554753358af2b6522d0434

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
